import { PropsWithChildren } from "react";
import type { Metadata } from "next";
import { Layout } from "@/components/Layout";
import "@/assets/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <Layout>{props.children}</Layout>
      </body>
    </html>
  );
}
